posts_per_page: "1"
site_title: Hiram's Picks
social: hiramv
embedly_key: 0098312d92ca46b9a69779ebef3f080d
twitter_key: FVmrkq6bICc0HlpB3Sc7Ew
twitter_secret: 59EcZMKLoliaq2652b056jsXLmgYvmKqzkhkQJpLw